apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eziyge748-python 
  janus-idp.io/tekton: eziyge748-python
  backstage.io/kubernetes-id: eziyge748-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eziyge748-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml