apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: eziyge748-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:05f4f92d4be7641095d8841ed67688c1b8020c43@sha256:176258b1d8bb0a2ad4cf3677a21d753b1d04d222cc7ac58e51fa0263f83f91d5
          name: container-image
