apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: eziyge748-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eziyge748-python 
  name: eziyge748-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: eziyge748-python
    weight: 100 
